---
name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.23.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Test
        run: go test -v -race -coverprofile=coverage -covermode=atomic ./...
